require 'rspec'
require_relative '../lib/parking_lot'
require_relative '../lib/parking_boy'
require_relative '../lib/reporter'
require_relative '../lib/chooser_factory'
require_relative '../lib/parking_card'
require_relative '../lib/car'
require_relative '../lib/length'
